name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES
  
  ## Docker Images
  
  ```
  ghcr.io/jnewland/git-and-stuff:v$RESOLVED_VERSION
  jnewland/git-and-stuff:v$RESOLVED_VERSION
  ```
