name: release-drafter

on:
  push:
    branches:
      - main

jobs:
  release-drafter:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
