name: release-drafter

on:
  push:
    branches:
      - main

jobs:
  release-drafter:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@e9ee02fbac03d922bac6212003695e8358dd88b0 # tag=v5
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
