name: release-drafter

on:
  push:
    branches:
      - main

jobs:
  release-drafter:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@ac463ffd9cc4c6ad5682af93dc3e3591c4657ee3 # tag=v5
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
