name: renovate
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 */4 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          RENOVATE_AUTODISCOVER: 'false'
          RENOVATE_TOKEN: ${{ secrets.CR_PAT }}
          LOG_LEVEL: debug
          LOG_FORMAT: json
        run: |
          docker run --rm -i -v $(pwd):$(pwd) -w $(pwd) -e LOG_LEVEL -e LOG_FORMAT -e RENOVATE_TOKEN \
            renovate/renovate:slim ${{ github.repository }} | tee renovate.jsonl
          if grep -i fail renovate.jsonl; then
            echo "::warning ::$(grep -i fail renovate.jsonl| jq -r .msg)"
          fi