name: renovate
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 */4 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p /tmp/renovate
      - name: renovate cache
        uses: actions/cache@v2
        with:
          path: /tmp/renovate/cache
          key: ${{ runner.os }}-v1-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-v1-

      - env:
          RENOVATE_AUTODISCOVER: 'false'
          RENOVATE_TOKEN: ${{ secrets.UR_BOT_TOKEN }}
          LOG_LEVEL: debug
          LOG_FORMAT: json
        run: |
          docker run --rm -i --user $UID -v $(pwd):$(pwd) -v /tmp/renovate:/tmp/renovate -w $(pwd) -e LOG_LEVEL -e LOG_FORMAT -e RENOVATE_TOKEN \
            renovate/renovate:slim ${{ github.repository }} | tee renovate.jsonl
          if grep -i fail renovate.jsonl; then
            echo "::warning ::$(grep -i fail renovate.jsonl| jq -r .msg)"
          fi
          if grep -i '"err"' renovate.jsonl; then
            echo "::error ::$(grep -i '"err"' renovate.jsonl| jq -r .msg)"
            exit 1
          fi
