name: sync-lockfile
on:
  workflow_dispatch:
  push:
jobs:
  sync-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          pull: true
          push: false
          tags: ${{ github.event.repository.name }}
          cache-from: |
            type=registry,ref=${{ github.repository }}:cache
            type=local,src=/tmp/.buildx-cache
          load: true
          cache-to: mode=max,type=local,dest=/tmp/.buildx-cache

      - run: make check
      - name: sync Aptfile.lock
        if: failed()
        env:
          BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "hubot@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -am "sync Aptfile.lock"

          echo "::error ::Aptfile.lock outdated"

          GITHUB_USER=$(echo ${GITHUB_REPOSITORY} | cut -f 1 -d /)
          cat >> ~/.netrc <<EOF
          machine github.com
            login $GITHUB_USER
            password $BOT_TOKEN
          EOF
          git remote set-url origin "https://github.com/${GITHUB_REPOSITORY}"

          # Push & rebase 5 times
          rebases=0
          until [ $rebases -ge 5 ]; do
            if git push origin HEAD:${GITHUB_REF}; then
              echo "::error ::Aptfile.lock update pushed. Please re-trigger the sync-lock workflow on this branch to confirm."
              exit 1
            else
              git pull --rebase origin ${GITHUB_REF}
            fi
            rebases=$[$rebases+1]
          done
          exit 1