name: validate-renovate
on:
  workflow_dispatch:
  push:
jobs:
  validate-renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm -i -v $(pwd):$(pwd) -w $(pwd) -e LOG_LEVEL=debug renovate/renovate:slim renovate-config-validator
      - env:
          RENOVATE_TOKEN: ${{ secrets.CR_PAT }}
        run: docker run --rm -i -v $(pwd):$(pwd) -w $(pwd) -e LOG_LEVEL=debug -e RENOVATE_TOKEN renovate/renovate:slim ${{ github.repository }} --dry-run