name: validate-renovate
on:
  workflow_dispatch:
  push:
jobs:
  validate-renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker run --rm -i -v $(pwd):$(pwd) -w $(pwd) -e $RENOVATE_TOKEN renovate/renovate:slim ${{ github.repository }} --dry-run