name: validate-renovate
on:
  workflow_dispatch:
  push:
jobs:
  validate-renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          LOG_LEVEL: debug
        run: |
          docker run --rm -i -v $(pwd):$(pwd) -w $(pwd) -e LOG_LEVEL \
            renovate/renovate:slim renovate-config-validator